name: Build and Push Docker Image
 
on:
  push:
    branches: 
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/k8s-demo
          docker build -t $IMAGE_NAME:${{ github.run_number }} .
 
      - name: Push Docker Image
        run: |

           docker push $IMAGE_NAME:${{ github.run_number }}
